### ISSUE TITLE
Disable blink animation on refresh of codeview

### ISSUE THREAD

**Issue by alokomkar** [kbiakov/CodeView-android#25]
How do I disable blink animation when a codeview is reset. 
`programCodeView.setOptions(Options.Default.get(getContext())
                .withLanguage(programLanguage)
                .withCode(programLines)
                .withTheme(ColorTheme.MONOKAI));`

This code is used to set program lines to the code view, there's a blink which happens at this point. Can it be disabled?

**Comment by kbiakov** [comment]
Hi, thanks for reporting the issue! Fixed in latest release, use option:
```
options.disableHighlightAnimation()
```
