### ISSUE TITLE
Initial tab/space is trimmed at the starting of each new line

### ISSUE THREAD

**Issue by khokharnikunj8** [kbiakov/CodeView-android#29]
I have recently used this library to highlight the syntax. But it trimmed initial spaces and white space characters at the beginning of each new line.  This has made difficult to understand the code. Please add this feature.

**Comment by kbiakov** [comment]
Hi, thanks for reporting the issue! Fixed and soon will be published in forthcoming release.

**Comment by khokharnikunj8** [comment]
@kbiakov  can I work on this issue and open PR?

**Comment by kbiakov** [comment]
Yesterday I found new issue which breaks highlighting: it's fixed, but not merged to `develop` branch. Also I need to fix Travis CI build fail related to not applied licenses. If you want to - you can, but as I think it's more convenient to do it by my own.

**Comment by kbiakov** [comment]
Hi, check latest release! Note that I moved repository under my ownership: see dependency in README.
