### ISSUE TITLE
CodeView appears in 2s and then disappear, except 1st line

### ISSUE THREAD

**Issue by lilliCao** [kbiakov/CodeView-android#38]
I have one Activity just to show the CodeView. It appears at the first time I start the Activity.
When I restart the activity, it appears like in 2s and then disappears. I have no error, no special warning, etc
see more
https://github.com/lilliCao/javoid
I followed your instruction and only used default value.

**Comment by TADraeseke** [comment]
I have the same problem. How did you resolve this?

**Comment by lilliCao** [comment]
I actually did not know how the problem was solved. I have just test around some set up for the CodeView.
The version, that later on worked for my project is to find here
https://github.com/lilliCao/javoid/blob/master/Javoid/app/src/main/java/com/example/android/javoid/CodeSnippetActivity.java

**Comment by lilliCao** [comment]
I actually did not know how the problem was solved. I have just test around some set up for the CodeView.
The version, that later on worked for my project is to find here
https://github.com/lilliCao/javoid/blob/master/Javoid/app/src/main/java/com/example/android/javoid/CodeSnippetActivity.java

**Comment by pboymt** [comment]
you can use `disableHighlightAnimation()`. I thought the appearance of this bug was due to the inverse of default highlight animation.
