### ISSUE TITLE
How wrap code to next line?

### ISSUE THREAD

**Issue by AdityaAnand1** [kbiakov/CodeView-android#39]
I need to put codeview in a scrolling element, but because of [this issue](https://github.com/kbiakov/CodeView-android/issues/27) I can't so I'm trying to figure out a workaround by disabling `clickable` on the codeview, but then I can't have code that isn't visible because it's off screen.

For me, it's okay if the code isn't clickable/scrollable/selectable. Is there a way to wrap code to the next line?

**Comment by kbiakov** [comment]
Need some time to investigation, stay tuned here: #27
