### ISSUE TITLE
How do we increase the code font size 

### ISSUE THREAD

**Issue by MShamshuddeen** [kbiakov/CodeView-android#40]

**Comment by kbiakov** [comment]
Hi! Try [this one](https://github.com/kbiakov/CodeView-android#font).

**Comment by MShamshuddeen** [comment]
i didn't understand can you more elaborate on that.Where i need to pass the fontSize

**Comment by kbiakov** [comment]
By updating [options](https://github.com/kbiakov/CodeView-android#options), you can set it this way:
```Kotlin
myOptions.withFormat(Format.Compact.copy(fontSize = 15f))
```
And don't forget to check your markup to be sure that isn't broken, because larger font size requires larger space between lines. Just play with other params in [Format](https://github.com/kbiakov/CodeView-android#format). Hope it helps!

**Comment by MShamshuddeen** [comment]
codeView.setOptions(Options.Default.get(this)
                .withLanguage("python")
                .withCode(R.string.code5)
                .withTheme(ColorTheme.MONOKAI)
                .withFormat(Format.Compact.copy(fontSize=15f)));


after adding this m getting error 
Error:(24, 35) error: Compact has private access in Format
Error:(24, 49) error: cannot find symbol variable fontSize

**Comment by kbiakov** [comment]
If you use it from Java, you should create the instance of `Format` class and provide several params:
```Java
codeView.setOptions(Options.Default.get(this)
    .withLanguage("python")
    .withCode(R.string.code5)
    .withTheme(ColorTheme.MONOKAI)
    .withFormat(new Format(
        1,    // scale factor
        18,   // line height
        3,    // border height
        15    // font size
    ));
```
It's a good catch! At this moment it is not so simple and convenient to create format this way in cause of interoperability with Kotlin data classes which represents **Format**. I will improve Java support in next release.

_P.S._ The preceding constants was taken from [`Format.Compact`](https://github.com/kbiakov/CodeView-android/blob/088f98581945a2dc7fbc30600af6b63de462c9d2/codeview/src/main/java/io/github/kbiakov/codeview/adapters/AbstractCodeAdapter.kt#L443).

**Comment by kbiakov** [comment]
@MShamshuddeen @Rizwansyed9 That helped? Can I close the issue?

**Comment by MShamshuddeen** [comment]
Yes, Thanks for your Time and support

**Comment by femindharamshi** [comment]
So, i have added a button to zoom in,
but here is what happens on zooming in :
```
zoomIn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                zoom++; //a variable to keep track of current zoom level
                mCodeView.setOptions(Options.Default.get(HomeActivity.this)
                        .withLanguage("c")
                        .withCode(currentCode)
                        .withFont(Font.Consolas)
                        .withFormat(new Format(
                                1,    // scale factor
                                (zoom+(int)(zoom*0.30)),   // line height
                                3,    // border height
                                zoom    // font size
                        ))
                        .withTheme(ColorTheme.MONOKAI));
            }
        });
```

but this refreshes the code, can't i just change the format without re-initializing the whole code in the code view ? is that possible ?
