### ISSUE TITLE
Project versions out-of-date

### ISSUE THREAD

**Issue by Brainsucker92** [kbiakov/CodeView-Android#53]
Hello there,

after improting this project into my IDE, it was screaming towards me the project is using various outdated dependency resources. Only after updating all of them I was able to build the project properly.

In particular I had to update all `build.gradle` files as well as the `gradle-wrapper.properties` file in order to make the project build again in Android Studio.
So before opening a pull-request straight away to fix those issues I wanted to make sure if there is not any particular reason not to update all that stuff?

**Comment by kbiakov** [comment]
See #56
